import type { MushroomSite } from "./types";

export const SITES: MushroomSite[] = [
  {
    id: "pariana-pasquilio",
    name: "Pariana – Pasquilio",
    municipality: "Massa",
    province: "MS",
    region: "Toscana",
    center: { lat: 44.086, lon: 10.175 },
    bounds: { south: 44.06, west: 10.14, north: 44.11, east: 10.21 },
    elevationMin: 650,
    elevationMax: 1350,
    area: "versante Tirreno, Alpi Apuane",
    geology: "calcareo-dolomitico, flysch arenaceo, argilliti",
    slope: "ripido, esposizione ovest-sudovest",
    rainfall: "1400–1800 mm/anno, nebbia estiva frequente",
    iemStation: "LIML",
    asosStation: "LIML",
    weatherLabel: "Massa (LIML)",
    gridFile: "grid-massa.json",
    description:
      "Versante tirrenico delle Alpi Apuane, dal Castello di Gragnana (650 m) al crinale del Monte Pasquilio (1.350 m). Faggete, castagneti da frutto e boschi misti su substrato calcareo-dolomitico. Zone di raccolta: Costa Palombaia, Canalaccio, Sorgente delle Canevone, Sorgente della Salsa, Passo Tambura.",
    trees: [
      { name: "Faggio", latin: "Fagus sylvatica", elevation: "900–1350 m", role: "dominante in alta quota, micorrizico" },
      { name: "Castagno", latin: "Castanea sativa", elevation: "650–1000 m", role: "castagneti da frutto, micorrizico" },
      { name: "Leccio", latin: "Quercus ilex", elevation: "650–850 m", role: "versante soleggiato, micorrizico" },
      { name: "Roverella", latin: "Quercus pubescens", elevation: "650–900 m", role: "versante xerico, micorrizico" },
      { name: "Carpino nero", latin: "Ostrya carpinifolia", elevation: "700–1100 m", role: "bosco misto, micorrizico" },
      { name: "Orniello", latin: "Fraxinus ornus", elevation: "650–1000 m", role: "bosco misto" },
      { name: "Pino marittimo", latin: "Pinus pinaster", elevation: "650–900 m", role: "rimboschimenti, micorrizico" },
      { name: "Abete bianco", latin: "Abies alba", elevation: "1000–1300 m", role: "nuclei relitti, micorrizico" },
    ],
    species: [
      { name: "Porcino", latin: "Boletus edulis", season: "set–nov", habitat: "faggeta, castagneto", notes: "specie principale, dopo piogge autunnali" },
      { name: "Porcino nero", latin: "Boletus aereus", season: "giu–set", habitat: "lecceta, roverella", notes: "estivo, versante soleggiato" },
      { name: "Porcino pinicola", latin: "Boletus pinophilus", season: "set–nov", habitat: "faggeta, pino", notes: "più tardivo del edulis" },
      { name: "Galletto", latin: "Cantharellus cibarius", season: "giu–ott", habitat: "faggeta umida, muschio", notes: "Canalaccio, Sorgente Salsa" },
      { name: "Ovolo buono", latin: "Amanita caesarea", season: "giu–set", habitat: "castagneto, roverella", notes: "estivo, dopo temporali" },
      { name: "Finferle", latin: "Craterellus lutescens", season: "ott–dic", habitat: "conifere, umido", notes: "tardivo, pinete" },
      { name: "Prugnolo", latin: "Calocybe gambosa", season: "apr–mag", habitat: "bosco misto, orli", notes: "primaverile" },
      { name: "Imbutino", latin: "Infundibulicybe geotropa", season: "ott–nov", habitat: "faggeta, radure", notes: "autunnale tardivo" },
    ],
    zones: [
      {
        id: "costa-palombaia",
        name: "Costa Palombaia",
        type: "castagneto/faggeta",
        elevation: "800–1100 m",
        description: "Versante occidentale sotto il crinale, mix di castagno e faggio. Zona classica per porcini dopo le piogge di settembre.",
      },
      {
        id: "canalaccio",
        name: "Canalaccio",
        type: "faggeta umida",
        elevation: "900–1200 m",
        description: "Impluvio fresco e umido, muschio abbondante. Galletti e porcini. Nebbia frequente in estate.",
      },
      {
        id: "sorgente-canevone",
        name: "Sorgente delle Canevone",
        type: "faggeta",
        elevation: "1000–1200 m",
        description: "Zona di alta quota intorno alla sorgente, faggio puro. Porcini pinicola e edulis.",
      },
      {
        id: "sorgente-salsa",
        name: "Sorgente della Salsa",
        type: "faggeta/muschio",
        elevation: "950–1150 m",
        description: "Ambiente umido permanente, muschio e humus. Galletti, finferle in autunno.",
      },
      {
        id: "passo-tambura",
        name: "Passo Tambura",
        type: "crinale/faggeta",
        elevation: "1100–1350 m",
        description: "Crinale ventoso tra Massa e Garfagnana. Faggeta d'alta quota, stagione più breve e tardiva.",
      },
    ],
  },
];
