import type { SitePoint } from "./types";

export const SITES_MASSA: SitePoint[] = [
  {
    id: "m1",
    name: "Castello di Gragnana",
    type: "castello",
    lat: 44.0785,
    lon: 10.1682,
    elevation: 280,
    description: "Punto di partenza storico, castello medievale. Quota bassa, lecceta e macchia mediterranea.",
  },
  {
    id: "m2",
    name: "Pariana",
    type: "paese",
    lat: 44.082,
    lon: 10.172,
    elevation: 350,
    description: "Frazione di Massa, accesso principale al versante. Castagneti da frutto nelle vicinanze.",
  },
  {
    id: "m3",
    name: "Resceto",
    type: "paese",
    lat: 44.075,
    lon: 10.155,
    elevation: 420,
    description: "Frazione a ovest, accesso al Canalaccio. Castagneti e bosco misto.",
  },
  {
    id: "m4",
    name: "Antona",
    type: "paese",
    lat: 44.09,
    lon: 10.185,
    elevation: 480,
    description: "Frazione a est, verso il Passo del Vestito. Castagneti e roverella.",
  },
  {
    id: "m5",
    name: "Canevara",
    type: "paese",
    lat: 44.07,
    lon: 10.16,
    elevation: 180,
    description: "Frazione bassa, fondovalle. Leccio e macchia, poco interessante per i funghi.",
  },
  {
    id: "m6",
    name: "Forno",
    type: "paese",
    lat: 44.065,
    lon: 10.145,
    elevation: 150,
    description: "Frazione di fondovalle, accesso da Massa città. Quota troppo bassa.",
  },
  {
    id: "m7",
    name: "Bergiola",
    type: "paese",
    lat: 44.085,
    lon: 10.14,
    elevation: 380,
    description: "Frazione nord-ovest, versante verso Carrara. Bosco misto, roverella.",
  },
  {
    id: "m8",
    name: "Costa Palombaia",
    type: "versante",
    lat: 44.088,
    lon: 10.178,
    elevation: 950,
    description: "Versante classico per porcini. Castagno e faggio, esposizione ovest. Dopo piogge di settembre.",
  },
  {
    id: "m9",
    name: "Canalaccio",
    type: "impluvio",
    lat: 44.086,
    lon: 10.17,
    elevation: 1050,
    description: "Impluvio umido, muschio abbondante. Galletti e porcini. Nebbia estiva frequente.",
  },
  {
    id: "m10",
    name: "Sorgente delle Canevone",
    type: "sorgente",
    lat: 44.092,
    lon: 10.182,
    elevation: 1100,
    description: "Sorgente in faggeta d'alta quota. Porcini pinicola e edulis. Ambiente fresco.",
  },
  {
    id: "m11",
    name: "Sorgente della Salsa",
    type: "sorgente",
    lat: 44.084,
    lon: 10.175,
    elevation: 1050,
    description: "Sorgente permanente, muschio e humus. Galletti, finferle in autunno inoltrato.",
  },
  {
    id: "m12",
    name: "Passo del Vestito",
    type: "passo",
    lat: 44.095,
    lon: 10.195,
    elevation: 1041,
    description: "Passo stradale tra Massa e Arni. Faggeta, vento. Stagione più breve.",
  },
  {
    id: "m13",
    name: "Passo Tambura",
    type: "passo",
    lat: 44.1,
    lon: 10.2,
    elevation: 1620,
    description: "Crinale tra Massa e Garfagnana. Faggeta d'alta quota, stagione tardiva e breve.",
  },
  {
    id: "m14",
    name: "Monte Pasquilio",
    type: "cima",
    lat: 44.098,
    lon: 10.188,
    elevation: 1489,
    description: "Cima del crinale, praterie e faggeta rada. Poco produttivo, troppo esposto.",
  },
  {
    id: "m15",
    name: "Monte Folgorito",
    type: "cima",
    lat: 44.105,
    lon: 10.175,
    elevation: 1214,
    description: "Cima a nord, verso Carrara. Faggeta e praterie. Porcini in settembre-ottobre.",
  },
  {
    id: "m16",
    name: "Foce di Pianza",
    type: "passo",
    lat: 44.11,
    lon: 10.165,
    elevation: 1268,
    description: "Passo verso Carrara, faggeta. Ambiente fresco, stagione tardiva.",
  },
  {
    id: "m17",
    name: "Valle del Frigido",
    type: "valle",
    lat: 44.06,
    lon: 10.15,
    elevation: 100,
    description: "Fondovalle del Frigido, troppo basso e antropizzato. Non interessante.",
  },
  {
    id: "m18",
    name: "Castagneto di Pariana",
    type: "castagneto",
    lat: 44.083,
    lon: 10.174,
    elevation: 450,
    description: "Castagneti da frutto tradizionali. Porcini aereus in estate, edulis in autunno.",
  },
  {
    id: "m19",
    name: "Lecceta di Gragnana",
    type: "lecceta",
    lat: 44.077,
    lon: 10.165,
    elevation: 320,
    description: "Lecceta su versante soleggiato. Porcino nero (aereus) in estate dopo temporali.",
  },
  {
    id: "m20",
    name: "Pineta di Antona",
    type: "pineta",
    lat: 44.088,
    lon: 10.19,
    elevation: 550,
    description: "Rimboschimento di pino marittimo. Finferle in autunno, qualche porcino pinicola.",
  },
];
