import type { AreaId } from "./geo";
import type { Aspect, Habitat } from "./types";

export type LocalRow = [
  id: string,
  name: string,
  comune: string,
  lat: number,
  lon: number,
  habitat: Habitat,
  area: AreaId,
  edge?: boolean,
  aspect?: Aspect,
];

export const MASSA_SITES_A: LocalRow[] = [
  ["ms-brugiana", "Monte Brugiana", "Massa", 44.051, 10.118, "castagno", "colline", true, "N"],
  ["ms-antona", "Antona – castagneti", "Massa", 44.069, 10.186, "castagno", "colline", true, "E"],
  ["ms-altagnana", "Altagnana", "Massa", 44.063, 10.198, "castagno", "colline", false, "E"],
  ["ms-pariana", "Pariana", "Massa", 44.056, 10.176, "castagno", "colline", true, "S"],
  ["ms-pariana-sopra", "Castagneti sopra Pariana", "Massa", 44.0605, 10.178, "castagno", "colline", true, "E"],
  ["ms-pariana-altagnana", "Pariana – verso Altagnana", "Massa", 44.059, 10.188, "castagno", "colline", true, "E"],
  ["ms-pasquilio", "Pasquilio – piazzale", "Montignoso", 44.0314, 10.1925, "conifera", "colline", true, "S"],
  ["ms-pasquilio-abetine", "Pasquilio – abetine", "Montignoso", 44.0335, 10.196, "conifera", "colline", false, "E"],
  ["ms-pasquilio-chiesetta", "Pasquilio – sacrario", "Montignoso", 44.0322, 10.1985, "misto", "colline", true, "S"],
  ["ms-pasquilio-prati", "Prati del Pasquilio", "Montignoso", 44.0298, 10.188, "pascolo", "colline", true, "S"],
  ["ms-campaccio", "Foce del Campaccio", "Montignoso", 44.038, 10.208, "faggio", "apuane", true, "E"],
  ["ms-termo", "Il Termo", "Montignoso", 44.0365, 10.202, "misto", "apuane", true, "E"],
  ["ms-carchio", "Monte Carchio", "Montignoso", 44.0336, 10.216, "faggio", "apuane", false, "S"],
  ["ms-folgorito", "Monte Folgorito", "Montignoso", 44.0239, 10.2067, "faggio", "apuane", false, "S"],
  ["ms-forche", "Passo delle Forche", "Montignoso", 44.028, 10.211, "faggio", "apuane", true, "E"],
  ["ms-eustachio", "Sant'Eustachio", "Montignoso", 44.0185, 10.176, "castagno", "colline", true, "S"],
  ["ms-cerreto-monti", "Cerreto di Montignoso", "Montignoso", 44.022, 10.184, "castagno", "colline", true, "N"],
  ["ms-resceto", "Resceto", "Massa", 44.082, 10.198, "castagno", "colline", false, "N"],
  ["ms-forno", "Forno di Massa", "Massa", 44.054, 10.168, "castagno", "colline", true, "E"],
  ["ms-canevara", "Canevara", "Massa", 44.046, 10.158, "castagno", "colline", true, "S"],
  ["ms-sancarlo", "San Carlo Terme", "Massa", 44.049, 10.152, "misto", "colline", true, "S"],
  ["ms-fioba", "Pian della Fioba", "Massa", 44.076, 10.192, "faggio", "apuane", false, "N"],
  ["ms-casania", "Casania", "Massa", 44.072, 10.172, "castagno", "colline", true, "E"],
  ["ms-bergiola", "Bergiola Maggiore", "Carrara", 44.073, 10.118, "castagno", "colline", true, "S"],
  ["ms-torano", "Torano", "Carrara", 44.071, 10.108, "misto", "colline", true, "S"],
  ["ms-miseglia", "Miseglia", "Carrara", 44.076, 10.128, "castagno", "colline", true, "E"],
  ["ms-colonnata", "Colonnata – castagneti", "Carrara", 44.087, 10.156, "castagno", "colline", true, "N"],
  ["ms-bedizzano", "Bedizzano", "Carrara", 44.089, 10.118, "castagno", "colline", true, "N"],
  ["ms-gragnana", "Gragnana", "Carrara", 44.096, 10.086, "castagno", "colline", true, "N"],
  ["ms-castelpoggio", "Castelpoggio", "Carrara", 44.108, 10.118, "castagno", "colline", true, "N"],
  ["ms-sorgnano", "Sorgnano", "Carrara", 44.092, 10.102, "castagno", "colline", true, "W"],
  ["ms-codena", "Codena", "Carrara", 44.082, 10.112, "misto", "colline", true, "S"],
  ["ms-fossone", "Fossone", "Carrara", 44.068, 10.092, "misto", "colline", true, "S"],
  ["ms-montignoso-castagni", "Montignoso – versante Brugiana", "Montignoso", 44.028, 10.168, "castagno", "colline", true, "N"],
  ["ms-cimitero-montignoso", "Cinquale interno – pineta umida", "Montignoso", 44.012, 10.158, "macchia", "colline", true, "S"],
  ["ms-fosdinovo", "Fosdinovo – sopra il castello", "Fosdinovo", 44.134, 10.018, "castagno", "colline", true, "S"],
  ["ms-caniparola", "Caniparola – collina", "Fosdinovo", 44.122, 10.002, "misto", "colline", true, "S"],
  ["ms-pulica", "Pulica", "Fosdinovo", 44.146, 10.038, "castagno", "colline", true, "N"],
  ["ms-tendola", "Tendola", "Fosdinovo", 44.154, 10.024, "castagno", "colline", true, "N"],
  ["ms-marciaso", "Marciaso", "Fosdinovo", 44.148, 10.056, "castagno", "colline", true, "N"],
  ["ms-ponzanello", "Ponzanello", "Fosdinovo", 44.126, 10.046, "misto", "colline", true, "S"],
  ["ms-giucano", "Giucano", "Fosdinovo", 44.118, 10.028, "castagno", "colline", true, "S"],
  ["ms-castedo", "Monte Castedo", "Fosdinovo", 44.156, 10.006, "quercia", "colline", true, "W"],
  ["ms-campocecina", "Campocecina", "Carrara", 44.102, 10.142, "faggio", "apuane", true, "N"],
  ["ms-pianza", "Foce di Pianza", "Carrara", 44.108, 10.156, "faggio", "apuane", true, "N"],
  ["ms-borla", "Monte Borla", "Carrara", 44.112, 10.152, "faggio", "apuane", false, "N"],
  ["ms-sagro-carrara", "Monte Sagro – versante Carrara", "Carrara", 44.118, 10.162, "faggio", "apuane", false, "W"],
  ["ms-sagro-vinca", "Monte Sagro – versante Vinca", "Fivizzano", 44.128, 10.168, "faggio", "apuane", false, "N"],
  ["ms-vinca", "Vinca", "Fivizzano", 44.127, 10.164, "faggio", "apuane", true, "N"],
  ["ms-equi", "Equi Terme – boschi sopra il paese", "Fivizzano", 44.148, 10.152, "misto", "apuane", true, "N"],
  ["ms-monzone", "Monzone", "Fivizzano", 44.162, 10.128, "castagno", "apuane", true, "N"],
  ["ms-aiola", "Aiola", "Fivizzano", 44.156, 10.154, "faggio", "apuane", false, "N"],
  ["ms-tenerano", "Tenerano", "Fivizzano", 44.146, 10.136, "castagno", "apuane", true, "N"],
  ["ms-monte-bianchi", "Monte dei Bianchi", "Fivizzano", 44.176, 10.146, "castagno", "lunigiana", true, "N"],
  ["ms-ugliancaldo", "Ugliancaldo", "Casola in Lunigiana", 44.154, 10.206, "faggio", "apuane", false, "N"],
  ["ms-codiponte", "Codiponte", "Casola in Lunigiana", 44.174, 10.164, "castagno", "apuane", true, "N"],
  ["ms-argigliano", "Argigliano", "Casola in Lunigiana", 44.186, 10.186, "faggio", "apuane", false, "N"],
  ["ms-casola", "Casola – versante Apuane", "Casola in Lunigiana", 44.198, 10.176, "faggio", "apuane", true, "N"],
  ["ms-reusa", "Reusa", "Casola in Lunigiana", 44.206, 10.196, "faggio", "apuane", false, "E"],
  ["ms-offiano", "Offiano", "Casola in Lunigiana", 44.214, 10.166, "misto", "lunigiana", true, "N"],
  ["ms-vestito", "Passo del Vestito", "Massa", 44.078, 10.218, "faggio", "apuane", true, "E"],
  ["ms-arni", "Arni – orlo della conca", "Stazzema", 44.086, 10.228, "faggio", "apuane", true, "N"],
  ["ms-minucciano", "Minucciano – Pieve", "Minucciano", 44.174, 10.218, "faggio", "apuane", true, "N"],
  ["ms-gramolazzo", "Gramolazzo – boschi del lago", "Minucciano", 44.158, 10.268, "faggio", "apuane", true, "N"],
  ["ms-vagli", "Vagli di Sopra", "Vagli Sotto", 44.116, 10.248, "faggio", "apuane", false, "N"],
  ["ms-isola-santa", "Isola Santa", "Careggine", 44.066, 10.258, "faggio", "apuane", true, "N"],
  ["ms-tambura", "Foce Tambura – versante Massa", "Massa", 44.098, 10.218, "faggio", "apuane", false, "N"],
  ["ms-altissimo", "Monte Altissimo – versante Forno", "Massa", 44.092, 10.232, "faggio", "apuane", false, "W"],
  ["ms-mosceta", "Foce di Mosceta", "Stazzema", 44.072, 10.242, "faggio", "apuane", true, "N"],
  ["ms-fivizzano", "Fivizzano – sopra Verrucola", "Fivizzano", 44.236, 10.122, "castagno", "lunigiana", true, "N"],
  ["ms-verrucola", "Verrucola", "Fivizzano", 44.226, 10.116, "castagno", "lunigiana", true, "N"],
  ["ms-soliera", "Soliera Apuana", "Fivizzano", 44.186, 10.126, "castagno", "lunigiana", true, "N"],
  ["ms-gragnola", "Gragnola – collina", "Fivizzano", 44.196, 10.104, "castagno", "lunigiana", true, "S"],
  ["ms-ceserano", "Ceserano", "Fivizzano", 44.206, 10.114, "castagno", "lunigiana", true, "N"],
  ["ms-sassalbo", "Sassalbo", "Fivizzano", 44.226, 10.236, "faggio", "appennino", true, "N"],
];
