import type { AreaId } from "./geo";
import type { Aspect, Habitat } from "./types";

export type LocalRow = [
  id: string,
  name: string,
  comune: string,
  lat: number,
  lon: number,
  habitat: Habitat,
  area: AreaId,
  edge?: boolean,
  aspect?: Aspect,
];

export const MASSA_SITES_B: LocalRow[] = [
  ["ms-magliano", "Magliano", "Fivizzano", 44.224, 10.086, "castagno", "lunigiana", true, "S"],
  ["ms-turano", "Turano", "Fivizzano", 44.216, 10.154, "castagno", "lunigiana", true, "N"],
  ["ms-debico", "Debicò", "Fivizzano", 44.246, 10.096, "castagno", "lunigiana", true, "N"],
  ["ms-apella", "Apella", "Fivizzano", 44.256, 10.116, "faggio", "lunigiana", false, "N"],
  ["ms-colla", "Colla", "Fivizzano", 44.266, 10.136, "faggio", "lunigiana", false, "N"],
  ["ms-tea", "Passo di Tea", "Fivizzano", 44.254, 10.186, "faggio", "lunigiana", true, "N"],
  ["ms-alebbio", "Alebbio", "Fivizzano", 44.216, 10.066, "castagno", "lunigiana", true, "S"],
  ["ms-mezzana", "Mezzana", "Fivizzano", 44.206, 10.086, "castagno", "lunigiana", true, "S"],
  ["ms-licciana", "Licciana Nardi – Monti", "Licciana Nardi", 44.246, 10.076, "castagno", "lunigiana", true, "N"],
  ["ms-tavernelle", "Tavernelle", "Licciana Nardi", 44.256, 10.056, "castagno", "lunigiana", true, "N"],
  ["ms-panicale", "Panicale", "Licciana Nardi", 44.238, 10.048, "castagno", "lunigiana", true, "S"],
  ["ms-varano", "Varano", "Licciana Nardi", 44.268, 10.042, "misto", "lunigiana", true, "N"],
  ["ms-terrarossa", "Terrarossa – collina", "Licciana Nardi", 44.216, 10.046, "quercia", "lunigiana", true, "S"],
  ["ms-comano", "Comano Castello", "Comano", 44.286, 10.126, "faggio", "lunigiana", true, "N"],
  ["ms-camporaghena", "Camporaghena", "Comano", 44.296, 10.146, "faggio", "appennino", false, "N"],
  ["ms-crespiano", "Crespiano", "Comano", 44.276, 10.116, "castagno", "lunigiana", true, "N"],
  ["ms-prota", "Prota", "Comano", 44.266, 10.106, "castagno", "lunigiana", true, "N"],
  ["ms-torsana", "Torsana", "Comano", 44.302, 10.118, "faggio", "appennino", false, "N"],
  ["ms-aulla-bibola", "Bibola", "Aulla", 44.198, 9.992, "castagno", "lunigiana", true, "S"],
  ["ms-vecchietto", "Vecchietto", "Aulla", 44.206, 10.012, "castagno", "lunigiana", true, "N"],
  ["ms-pallerone", "Pallerone – collina", "Aulla", 44.188, 10.002, "misto", "lunigiana", true, "S"],
  ["ms-caprigliola", "Caprigliola – collina", "Aulla", 44.176, 9.968, "quercia", "lunigiana", true, "S"],
  ["ms-podenzana", "Podenzana – Montedivalli", "Podenzana", 44.202, 9.944, "castagno", "lunigiana", true, "S"],
  ["ms-montedivalli", "Montedivalli", "Podenzana", 44.194, 9.926, "misto", "lunigiana", true, "S"],
  ["ms-tresana", "Tresana – Barbarasco", "Tresana", 44.236, 9.934, "castagno", "lunigiana", true, "S"],
  ["ms-villa-tresana", "Villa di Tresana", "Tresana", 44.248, 9.914, "castagno", "lunigiana", true, "N"],
  ["ms-mulazzo", "Mulazzo – Groppoli", "Mulazzo", 44.296, 9.906, "castagno", "lunigiana", true, "N"],
  ["ms-montereggio", "Montereggio", "Mulazzo", 44.326, 9.866, "castagno", "lunigiana", true, "N"],
  ["ms-castevoli", "Castevoli", "Mulazzo", 44.306, 9.876, "castagno", "lunigiana", true, "N"],
  ["ms-arpiola", "Arpiola", "Mulazzo", 44.318, 9.888, "castagno", "lunigiana", true, "N"],
  ["ms-bagnone", "Bagnone – sopra il borgo", "Bagnone", 44.314, 9.996, "castagno", "lunigiana", true, "N"],
  ["ms-treschietto", "Treschietto", "Bagnone", 44.326, 10.016, "castagno", "lunigiana", true, "N"],
  ["ms-corlaga", "Corlaga", "Bagnone", 44.306, 10.026, "castagno", "lunigiana", true, "N"],
  ["ms-iera", "Iera", "Bagnone", 44.336, 10.006, "faggio", "lunigiana", false, "N"],
  ["ms-logarghena", "Prati di Logarghena", "Bagnone", 44.346, 10.026, "pascolo", "lunigiana", true, "N"],
  ["ms-compione", "Compione", "Bagnone", 44.326, 9.976, "castagno", "lunigiana", true, "N"],
  ["ms-mochignano", "Mochignano", "Bagnone", 44.338, 9.988, "faggio", "lunigiana", false, "N"],
  ["ms-villafranca", "Villafranca – Filetto", "Villafranca in Lunigiana", 44.286, 9.976, "castagno", "lunigiana", true, "S"],
  ["ms-virgoletta", "Virgoletta", "Villafranca in Lunigiana", 44.276, 9.966, "castagno", "lunigiana", true, "S"],
  ["ms-malgrate", "Malgrate", "Villafranca in Lunigiana", 44.292, 9.944, "misto", "lunigiana", true, "S"],
  ["ms-filattiera", "Filattiera – Caprio", "Filattiera", 44.344, 9.946, "castagno", "lunigiana", true, "N"],
  ["ms-ponticello", "Ponticello", "Filattiera", 44.356, 9.926, "castagno", "lunigiana", true, "N"],
  ["ms-gigliana", "Gigliana", "Filattiera", 44.366, 9.956, "faggio", "lunigiana", false, "N"],
  ["ms-sigillina", "Rocca Sigillina", "Filattiera", 44.356, 9.976, "castagno", "lunigiana", true, "N"],
  ["ms-scorcetoli", "Scorcetoli", "Filattiera", 44.338, 9.918, "misto", "lunigiana", true, "S"],
  ["ms-pontremoli-mignegno", "Mignegno", "Pontremoli", 44.386, 9.906, "castagno", "lunigiana", true, "N"],
  ["ms-guinadi", "Guinadi", "Pontremoli", 44.396, 9.866, "castagno", "lunigiana", true, "N"],
  ["ms-gravagna", "Gravagna", "Pontremoli", 44.406, 9.916, "faggio", "appennino", false, "N"],
  ["ms-cervara", "Cervara", "Pontremoli", 44.416, 9.896, "faggio", "appennino", false, "N"],
  ["ms-careola", "Careola", "Pontremoli", 44.416, 9.946, "faggio", "appennino", false, "N"],
  ["ms-oppilo", "Oppilo", "Pontremoli", 44.386, 9.856, "castagno", "lunigiana", true, "N"],
  ["ms-arzelato", "Arzelato", "Pontremoli", 44.366, 9.846, "castagno", "lunigiana", true, "N"],
  ["ms-vignetolo", "Vignola di Pontremoli", "Pontremoli", 44.372, 9.872, "castagno", "lunigiana", true, "S"],
  ["ms-zeri-chiesa", "Chiesa di Zeri", "Zeri", 44.354, 9.764, "faggio", "appennino", true, "N"],
  ["ms-coloretta", "Coloretta", "Zeri", 44.346, 9.754, "faggio", "appennino", false, "N"],
  ["ms-patacini", "Patacini", "Zeri", 44.366, 9.786, "faggio", "appennino", false, "N"],
  ["ms-adelano", "Adelano", "Zeri", 44.336, 9.796, "castagno", "lunigiana", true, "N"],
  ["ms-noce", "Noce di Zeri", "Zeri", 44.376, 9.746, "faggio", "appennino", false, "N"],
  ["ms-ferriere", "Ferriere di Zeri", "Zeri", 44.348, 9.782, "faggio", "appennino", false, "N"],
  ["ms-cisa", "Passo della Cisa", "Pontremoli", 44.472, 9.928, "faggio", "appennino", true, "N"],
  ["ms-montelungo", "Montelungo", "Pontremoli", 44.426, 9.926, "faggio", "appennino", true, "N"],
  ["ms-brattello", "Foresta del Brattello", "Pontremoli", 44.408, 9.852, "faggio", "appennino", false, "N"],
  ["ms-passo-brattello", "Passo del Brattello", "Pontremoli", 44.416, 9.834, "faggio", "appennino", true, "N"],
  ["ms-prachiola", "Pracchiola", "Pontremoli", 44.426, 9.956, "faggio", "appennino", true, "N"],
  ["ms-due-santi", "Passo dei Due Santi", "Zeri", 44.358, 9.716, "faggio", "appennino", true, "N"],
  ["ms-gottero", "Monte Gottero", "Zeri", 44.386, 9.706, "faggio", "appennino", false, "N"],
  ["ms-molinatico", "Monte Molinatico", "Pontremoli", 44.438, 9.868, "faggio", "appennino", false, "N"],
  ["ms-cerreto", "Passo del Cerreto", "Fivizzano", 44.304, 10.234, "faggio", "appennino", true, "N"],
  ["ms-cerreto-laghi", "Cerreto Laghi – orlo", "Collagna", 44.308, 10.248, "faggio", "appennino", true, "N"],
  ["ms-nuda", "Monte La Nuda", "Fivizzano", 44.292, 10.214, "faggio", "appennino", false, "N"],
  ["ms-lagastrello", "Passo del Lagastrello", "Comano", 44.346, 10.176, "faggio", "appennino", true, "N"],
  ["ms-lago-paduli", "Lago Paduli – Lagastrello", "Comano", 44.342, 10.168, "faggio", "appennino", true, "N"],
  ["ms-succiso", "Succiso – versante Cerreto", "Ramiseto", 44.326, 10.266, "faggio", "appennino", true, "N"],
  ["ms-orsaro", "Monte Orsaro", "Pontremoli", 44.452, 9.978, "faggio", "appennino", false, "N"],
  ["ms-marmagna", "Monte Marmagna – versante Cisa", "Pontremoli", 44.458, 9.962, "faggio", "appennino", false, "N"],
];
