import { classifyTree } from "./trees";
import type { Habitat, Site } from "./types";

type Row = [
  id: string,
  name: string,
  region: string,
  province: string,
  lat: number,
  lon: number,
  habitat: Habitat,
  edge?: boolean,
];

const ITALY: Row[] = [
  ["paneveggio", "Foresta di Paneveggio", "Trentino-Alto Adige", "Trento", 46.308, 11.54, "conifera"],
  ["val-di-fiemme", "Val di Fiemme", "Trentino-Alto Adige", "Trento", 46.29, 11.47, "conifera"],
  ["carezza", "Latemar – Carezza", "Trentino-Alto Adige", "Bolzano", 46.347, 11.59, "conifera"],
  ["cansiglio", "Foresta del Cansiglio", "Veneto", "Belluno", 46.07, 12.41, "faggio"],
  ["asiago", "Altopiano di Asiago", "Veneto", "Vicenza", 45.875, 11.509, "faggio"],
  ["baldo", "Monte Baldo", "Veneto", "Verona", 45.72, 10.837, "faggio"],
  ["cortina", "Cortina – Faloria", "Veneto", "Belluno", 46.54, 12.135, "conifera"],
  ["tarvisio", "Foresta di Tarvisio", "Friuli-Venezia Giulia", "Udine", 46.505, 13.578, "conifera"],
  ["sauris", "Sauris – Carnia", "Friuli-Venezia Giulia", "Udine", 46.466, 12.708, "conifera"],
  ["cogne", "Cogne – Gran Paradiso", "Valle d'Aosta", "Aosta", 45.608, 7.356, "conifera"],
  ["salbertrand", "Gran Bosco di Salbertrand", "Piemonte", "Torino", 45.072, 6.888, "conifera"],
  ["alta-langa", "Alta Langa", "Piemonte", "Cuneo", 44.51, 8.21, "castagno", true],
  ["ossola", "Valle Ossola", "Piemonte", "Verbano-Cusio-Ossola", 46.12, 8.29, "conifera"],
  ["valdieri", "Valdieri – Alpi Marittime", "Piemonte", "Cuneo", 44.277, 7.398, "faggio"],
  ["penice", "Monte Penice", "Lombardia", "Pavia", 44.8, 9.32, "faggio"],
  ["orobie", "Orobie – Val Brembana", "Lombardia", "Bergamo", 45.95, 9.65, "misto"],
  ["stelvio", "Stelvio – val Zebrù", "Lombardia", "Sondrio", 46.47, 10.42, "conifera"],
  ["aveto", "Foresta dell'Aveto", "Liguria", "Genova", 44.45, 9.38, "faggio"],
  ["parmense", "Appennino Parmense", "Emilia-Romagna", "Parma", 44.45, 10.01, "faggio"],
  ["cimone", "Monte Cimone", "Emilia-Romagna", "Modena", 44.194, 10.701, "faggio"],
  ["camaldoli", "Camaldoli", "Toscana", "Arezzo", 43.813, 11.821, "faggio"],
  ["abetone", "Abetone", "Toscana", "Pistoia", 44.145, 10.665, "faggio"],
  ["amiata", "Monte Amiata", "Toscana", "Grosseto", 42.891, 11.626, "castagno"],
  ["vallombrosa", "Vallombrosa", "Toscana", "Firenze", 43.732, 11.558, "faggio"],
  ["casentino", "Foreste Casentinesi", "Toscana", "Arezzo", 43.78, 11.82, "faggio"],
  ["chianti", "Montagnola Senese", "Toscana", "Siena", 43.28, 11.25, "quercia", true],
  ["sibillini", "Monti Sibillini", "Marche", "Macerata", 42.824, 13.275, "faggio"],
  ["catria", "Monte Catria", "Marche", "Pesaro e Urbino", 43.462, 12.705, "faggio"],
  ["terminillo", "Terminillo", "Lazio", "Rieti", 42.473, 12.997, "faggio"],
  ["simbruini", "Livata – Simbruini", "Lazio", "Roma", 41.95, 13.11, "faggio"],
  ["gran-sasso", "Gran Sasso – Campo Imperatore", "Abruzzo", "L'Aquila", 42.44, 13.56, "faggio"],
  ["majella", "Majella – Blockhaus", "Abruzzo", "Pescara", 42.14, 14.11, "faggio"],
  ["pescasseroli", "Pescasseroli", "Abruzzo", "L'Aquila", 41.808, 13.79, "faggio"],
  ["laga", "Monti della Laga", "Abruzzo", "Teramo", 42.64, 13.46, "faggio"],
  ["matese", "Matese – Campitello", "Campania", "Caserta", 41.46, 14.39, "faggio"],
  ["umbra", "Foresta Umbra", "Puglia", "Foggia", 41.81, 16.0, "faggio"],
  ["cervati", "Monte Cervati", "Campania", "Salerno", 40.284, 15.428, "faggio"],
  ["sila-grande", "Sila Grande", "Calabria", "Cosenza", 39.35, 16.5, "conifera"],
  ["aspromonte", "Gambarie d'Aspromonte", "Calabria", "Reggio Calabria", 38.17, 15.87, "faggio"],
  ["pollino", "Pollino", "Basilicata", "Potenza", 39.92, 16.2, "faggio"],
  ["etna", "Linguaglossa – pineta", "Sicilia", "Catania", 37.84, 15.14, "conifera"],
  ["nebrodi", "Nebrodi", "Sicilia", "Messina", 37.95, 14.7, "faggio"],
  ["madonie", "Piano Battaglia", "Sicilia", "Palermo", 37.88, 14.02, "faggio"],
  ["gennargentu", "Gennargentu", "Sardegna", "Nuoro", 40.02, 9.32, "misto"],
  ["supramonte", "Supramonte – Lanaitto", "Sardegna", "Nuoro", 40.17, 9.49, "misto"],
];

export const ITALY_NAMED_SITES: Site[] = ITALY.map(
  ([id, name, region, province, lat, lon, habitat, edge]) => ({
    id,
    name,
    region,
    province,
    lat,
    lon,
    habitat,
    treeKind: classifyTree({ lat, lon, habitat }),
    edge,
    local: false,
    kind: "named",
    hotspot: "italia",
    aspect: "E",
  }),
);
