import type { LocalStation } from "./types";

/** Stazioni Aeronautica Militare / METAR italiane (rete IEM IT__ASOS). */
export const ITALY_ASOS: LocalStation[] = [
  {
    id: "eqys",
    icao: "EQYS",
    name: "Sigonella (US Navy)",
    network: "Aeronautica Militare / IEM",
    lat: 37.4,
    lon: 14.92,
    elevationM: 23,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liba",
    icao: "LIBA",
    name: "Foggia Amendola",
    network: "Aeronautica Militare / IEM",
    lat: 41.5381,
    lon: 15.7139,
    elevationM: 60,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libc",
    icao: "LIBC",
    name: "Crotone",
    network: "Aeronautica Militare / IEM",
    lat: 38.9967,
    lon: 17.0792,
    elevationM: 161,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libd",
    icao: "LIBD",
    name: "Bari Palese",
    network: "Aeronautica Militare / IEM",
    lat: 41.1381,
    lon: 16.765,
    elevationM: 44,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libe",
    icao: "LIBE",
    name: "Monte Sant'Angelo",
    network: "Aeronautica Militare / IEM",
    lat: 41.7084,
    lon: 15.9476,
    elevationM: 834,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libf",
    icao: "LIBF",
    name: "Foggia Gino Lisa",
    network: "Aeronautica Militare / IEM",
    lat: 41.4329,
    lon: 15.535,
    elevationM: 80,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libg",
    icao: "LIBG",
    name: "Taranto Grottaglie",
    network: "Aeronautica Militare / IEM",
    lat: 40.5172,
    lon: 17.3997,
    elevationM: 69,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libh",
    icao: "LIBH",
    name: "Marina di Ginosa",
    network: "Aeronautica Militare / IEM",
    lat: 40.4244,
    lon: 16.8867,
    elevationM: 12,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libn",
    icao: "LIBN",
    name: "Lecce Galatina",
    network: "Aeronautica Militare / IEM",
    lat: 40.2383,
    lon: 18.1389,
    elevationM: 61,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libp",
    icao: "LIBP",
    name: "Pescara",
    network: "Aeronautica Militare / IEM",
    lat: 42.4372,
    lon: 14.1872,
    elevationM: 11,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libq",
    icao: "LIBQ",
    name: "Monte Scuro",
    network: "Aeronautica Militare / IEM",
    lat: 39.3306,
    lon: 16.3964,
    elevationM: 1720,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libr",
    icao: "LIBR",
    name: "Brindisi",
    network: "Aeronautica Militare / IEM",
    lat: 40.6577,
    lon: 17.9514,
    elevationM: 10,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libt",
    icao: "LIBT",
    name: "Termoli",
    network: "Aeronautica Militare / IEM",
    lat: 42.0043,
    lon: 14.9965,
    elevationM: 44,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libu",
    icao: "LIBU",
    name: "Latronico",
    network: "Aeronautica Militare / IEM",
    lat: 40.0875,
    lon: 16.0136,
    elevationM: 896,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "libv",
    icao: "LIBV",
    name: "Gioia del Colle",
    network: "Aeronautica Militare / IEM",
    lat: 40.7661,
    lon: 16.9353,
    elevationM: 350,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liby",
    icao: "LIBY",
    name: "Santa Maria di Leuca",
    network: "Aeronautica Militare / IEM",
    lat: 39.8114,
    lon: 18.3422,
    elevationM: 112,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lica",
    icao: "LICA",
    name: "Lamezia Terme",
    network: "Aeronautica Militare / IEM",
    lat: 38.9083,
    lon: 16.2417,
    elevationM: 15,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licb",
    icao: "LICB",
    name: "Comiso",
    network: "Aeronautica Militare / IEM",
    lat: 36.9333,
    lon: 14.6,
    elevationM: 293,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licc",
    icao: "LICC",
    name: "Catania Fontanarossa",
    network: "Aeronautica Militare / IEM",
    lat: 37.4667,
    lon: 15.0639,
    elevationM: 17,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licd",
    icao: "LICD",
    name: "Lampedusa",
    network: "Aeronautica Militare / IEM",
    lat: 35.4981,
    lon: 12.6183,
    elevationM: 20,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lice",
    icao: "LICE",
    name: "Enna",
    network: "Aeronautica Militare / IEM",
    lat: 37.5681,
    lon: 14.2797,
    elevationM: 965,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licf",
    icao: "LICF",
    name: "Messina",
    network: "Aeronautica Militare / IEM",
    lat: 38.2,
    lon: 15.55,
    elevationM: 51,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licg",
    icao: "LICG",
    name: "Pantelleria",
    network: "Aeronautica Militare / IEM",
    lat: 36.8139,
    lon: 11.9711,
    elevationM: 191,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licj",
    icao: "LICJ",
    name: "Palermo Punta Raisi",
    network: "Aeronautica Militare / IEM",
    lat: 38.1819,
    lon: 13.0994,
    elevationM: 34,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licl",
    icao: "LICL",
    name: "Gela",
    network: "Aeronautica Militare / IEM",
    lat: 37.0764,
    lon: 14.225,
    elevationM: 33,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lico",
    icao: "LICO",
    name: "Cozzo Spadaro",
    network: "Aeronautica Militare / IEM",
    lat: 36.6861,
    lon: 15.1314,
    elevationM: 51,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licr",
    icao: "LICR",
    name: "Reggio Calabria",
    network: "Aeronautica Militare / IEM",
    lat: 38.0719,
    lon: 15.6536,
    elevationM: 21,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lict",
    icao: "LICT",
    name: "Trapani Birgi",
    network: "Aeronautica Militare / IEM",
    lat: 37.9142,
    lon: 12.4914,
    elevationM: 7,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licu",
    icao: "LICU",
    name: "Ustica",
    network: "Aeronautica Militare / IEM",
    lat: 38.7072,
    lon: 13.1772,
    elevationM: 251,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "licz",
    icao: "LICZ",
    name: "Sigonella",
    network: "Aeronautica Militare / IEM",
    lat: 37.4056,
    lon: 14.9186,
    elevationM: 22,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liea",
    icao: "LIEA",
    name: "Alghero Fertilia",
    network: "Aeronautica Militare / IEM",
    lat: 40.6311,
    lon: 8.2886,
    elevationM: 23,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lieb",
    icao: "LIEB",
    name: "Capo Bellavista",
    network: "Aeronautica Militare / IEM",
    lat: 39.9307,
    lon: 9.7132,
    elevationM: 156,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liec",
    icao: "LIEC",
    name: "Capo Carbonara",
    network: "Aeronautica Militare / IEM",
    lat: 39.1039,
    lon: 9.5135,
    elevationM: 118,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lied",
    icao: "LIED",
    name: "Decimomannu",
    network: "Aeronautica Militare / IEM",
    lat: 39.3461,
    lon: 8.9675,
    elevationM: 28,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liee",
    icao: "LIEE",
    name: "Cagliari Elmas",
    network: "Aeronautica Militare / IEM",
    lat: 39.2434,
    lon: 9.0603,
    elevationM: 4,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lieo",
    icao: "LIEO",
    name: "Olbia Costa Smeralda",
    network: "Aeronautica Militare / IEM",
    lat: 40.8986,
    lon: 9.5178,
    elevationM: 13,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lima",
    icao: "LIMA",
    name: "Torino Aeritalia",
    network: "Aeronautica Militare / IEM",
    lat: 45.0864,
    lon: 7.6034,
    elevationM: 287,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limc",
    icao: "LIMC",
    name: "Milano Malpensa",
    network: "Aeronautica Militare / IEM",
    lat: 45.63,
    lon: 8.7231,
    elevationM: 211,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lime",
    icao: "LIME",
    name: "Bergamo Orio al Serio",
    network: "Aeronautica Militare / IEM",
    lat: 45.6689,
    lon: 9.7003,
    elevationM: 237,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limf",
    icao: "LIMF",
    name: "Torino Caselle",
    network: "Aeronautica Militare / IEM",
    lat: 45.2025,
    lon: 7.6494,
    elevationM: 287,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limg",
    icao: "LIMG",
    name: "Albenga",
    network: "Aeronautica Militare / IEM",
    lat: 44.0458,
    lon: 8.1256,
    elevationM: 49,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limh",
    icao: "LIMH",
    name: "Plateau Rosa",
    network: "Aeronautica Militare / IEM",
    lat: 45.9352,
    lon: 7.7072,
    elevationM: 3488,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limj",
    icao: "LIMJ",
    name: "Genova Sestri",
    network: "Aeronautica Militare / IEM",
    lat: 44.4133,
    lon: 8.8375,
    elevationM: 3,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limk",
    icao: "LIMK",
    name: "Torino Bric della Croce",
    network: "Aeronautica Militare / IEM",
    lat: 45.0333,
    lon: 7.7317,
    elevationM: 710,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liml",
    icao: "LIML",
    name: "Milano Linate",
    network: "Aeronautica Militare / IEM",
    lat: 45.4614,
    lon: 9.2626,
    elevationM: 103,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limn",
    icao: "LIMN",
    name: "Cameri",
    network: "Aeronautica Militare / IEM",
    lat: 45.5296,
    lon: 8.6692,
    elevationM: 169,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limp",
    icao: "LIMP",
    name: "Parma",
    network: "Aeronautica Militare / IEM",
    lat: 44.8245,
    lon: 10.2964,
    elevationM: 50,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lims",
    icao: "LIMS",
    name: "Piacenza San Damiano",
    network: "Aeronautica Militare / IEM",
    lat: 44.9092,
    lon: 9.7278,
    elevationM: 138,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limt",
    icao: "LIMT",
    name: "Passo della Cisa",
    network: "Aeronautica Militare / IEM",
    lat: 44.4719,
    lon: 9.9286,
    elevationM: 1040,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limu",
    icao: "LIMU",
    name: "Capo Mele",
    network: "Aeronautica Militare / IEM",
    lat: 43.9572,
    lon: 8.1697,
    elevationM: 221,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limv",
    icao: "LIMV",
    name: "Passo dei Giovi",
    network: "Aeronautica Militare / IEM",
    lat: 44.5522,
    lon: 8.9375,
    elevationM: 475,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limw",
    icao: "LIMW",
    name: "Aosta",
    network: "Aeronautica Militare / IEM",
    lat: 45.7385,
    lon: 7.3687,
    elevationM: 545,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limy",
    icao: "LIMY",
    name: "Monte Malanotte",
    network: "Aeronautica Militare / IEM",
    lat: 44.25,
    lon: 7.8,
    elevationM: 1742,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "limz",
    icao: "LIMZ",
    name: "Cuneo Levaldigi",
    network: "Aeronautica Militare / IEM",
    lat: 44.547,
    lon: 7.6232,
    elevationM: 380,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipa",
    icao: "LIPA",
    name: "Aviano",
    network: "Aeronautica Militare / IEM",
    lat: 46.0286,
    lon: 12.6033,
    elevationM: 126,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipb",
    icao: "LIPB",
    name: "Bolzano",
    network: "Aeronautica Militare / IEM",
    lat: 46.4603,
    lon: 11.3264,
    elevationM: 241,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipc",
    icao: "LIPC",
    name: "Cervia",
    network: "Aeronautica Militare / IEM",
    lat: 44.2289,
    lon: 12.2919,
    elevationM: 10,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipe",
    icao: "LIPE",
    name: "Bologna",
    network: "Aeronautica Militare / IEM",
    lat: 44.5308,
    lon: 11.2969,
    elevationM: 42,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipf",
    icao: "LIPF",
    name: "Ferrara",
    network: "Aeronautica Militare / IEM",
    lat: 44.8156,
    lon: 11.6125,
    elevationM: 10,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liph",
    icao: "LIPH",
    name: "Treviso Sant'Angelo",
    network: "Aeronautica Militare / IEM",
    lat: 45.6484,
    lon: 12.1944,
    elevationM: 23,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipi",
    icao: "LIPI",
    name: "Rivolto",
    network: "Aeronautica Militare / IEM",
    lat: 45.9756,
    lon: 13.0492,
    elevationM: 53,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipk",
    icao: "LIPK",
    name: "Forlì",
    network: "Aeronautica Militare / IEM",
    lat: 44.1956,
    lon: 12.0697,
    elevationM: 32,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipl",
    icao: "LIPL",
    name: "Ghedi",
    network: "Aeronautica Militare / IEM",
    lat: 45.4206,
    lon: 10.2814,
    elevationM: 92,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipo",
    icao: "LIPO",
    name: "Brescia Montichiari",
    network: "Aeronautica Militare / IEM",
    lat: 45.4289,
    lon: 10.3306,
    elevationM: 109,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipq",
    icao: "LIPQ",
    name: "Trieste Ronchi dei Legionari",
    network: "Aeronautica Militare / IEM",
    lat: 45.8275,
    lon: 13.4722,
    elevationM: 12,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipr",
    icao: "LIPR",
    name: "Rimini",
    network: "Aeronautica Militare / IEM",
    lat: 44.0244,
    lon: 12.6128,
    elevationM: 13,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lips",
    icao: "LIPS",
    name: "Treviso Istrana",
    network: "Aeronautica Militare / IEM",
    lat: 45.6839,
    lon: 12.1067,
    elevationM: 41,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipu",
    icao: "LIPU",
    name: "Padova",
    network: "Aeronautica Militare / IEM",
    lat: 45.3958,
    lon: 11.8479,
    elevationM: 14,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipx",
    icao: "LIPX",
    name: "Verona Villafranca",
    network: "Aeronautica Militare / IEM",
    lat: 45.3875,
    lon: 10.8723,
    elevationM: 68,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipy",
    icao: "LIPY",
    name: "Ancona Falconara",
    network: "Aeronautica Militare / IEM",
    lat: 43.6167,
    lon: 13.3603,
    elevationM: 10,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lipz",
    icao: "LIPZ",
    name: "Venezia Tessera",
    network: "Aeronautica Militare / IEM",
    lat: 45.5053,
    lon: 12.3519,
    elevationM: 6,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liqb",
    icao: "LIQB",
    name: "Arezzo",
    network: "Aeronautica Militare / IEM",
    lat: 43.4597,
    lon: 11.8456,
    elevationM: 247,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liqc",
    icao: "LIQC",
    name: "Capri",
    network: "Aeronautica Militare / IEM",
    lat: 40.5582,
    lon: 14.2023,
    elevationM: 269,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liqj",
    icao: "LIQJ",
    name: "Civitavecchia",
    network: "Aeronautica Militare / IEM",
    lat: 42.0328,
    lon: 11.8331,
    elevationM: 4,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liqn",
    icao: "LIQN",
    name: "Rieti",
    network: "Aeronautica Militare / IEM",
    lat: 42.4267,
    lon: 12.85,
    elevationM: 389,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liqo",
    icao: "LIQO",
    name: "Monte Argentario",
    network: "Aeronautica Militare / IEM",
    lat: 42.3869,
    lon: 11.1697,
    elevationM: 632,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liqw",
    icao: "LIQW",
    name: "Sarzana-Luni",
    network: "Aeronautica Militare / IEM",
    lat: 44.0872,
    lon: 9.985,
    elevationM: 10,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lira",
    icao: "LIRA",
    name: "Roma Ciampino",
    network: "Aeronautica Militare / IEM",
    lat: 41.8078,
    lon: 12.5846,
    elevationM: 101,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirb",
    icao: "LIRB",
    name: "Vigna di Valle",
    network: "Aeronautica Militare / IEM",
    lat: 42.0803,
    lon: 12.2114,
    elevationM: 258,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lire",
    icao: "LIRE",
    name: "Pratica di Mare",
    network: "Aeronautica Militare / IEM",
    lat: 41.6545,
    lon: 12.4452,
    elevationM: 12,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirf",
    icao: "LIRF",
    name: "Roma Fiumicino",
    network: "Aeronautica Militare / IEM",
    lat: 41.8003,
    lon: 12.2389,
    elevationM: 3,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirg",
    icao: "LIRG",
    name: "Guidonia",
    network: "Aeronautica Militare / IEM",
    lat: 41.9967,
    lon: 12.7344,
    elevationM: 89,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirh",
    icao: "LIRH",
    name: "Frosinone",
    network: "Aeronautica Militare / IEM",
    lat: 41.645,
    lon: 13.2994,
    elevationM: 181,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liri",
    icao: "LIRI",
    name: "Salerno Pontecagnano",
    network: "Aeronautica Militare / IEM",
    lat: 40.6204,
    lon: 14.9113,
    elevationM: 40,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirj",
    icao: "LIRJ",
    name: "Marina di Campo",
    network: "Aeronautica Militare / IEM",
    lat: 42.7618,
    lon: 10.2393,
    elevationM: 397,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirk",
    icao: "LIRK",
    name: "Terminillo",
    network: "Aeronautica Militare / IEM",
    lat: 42.4667,
    lon: 12.9833,
    elevationM: 1875,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirl",
    icao: "LIRL",
    name: "Latina",
    network: "Aeronautica Militare / IEM",
    lat: 41.5458,
    lon: 12.9097,
    elevationM: 26,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirm",
    icao: "LIRM",
    name: "Grazzanise",
    network: "Aeronautica Militare / IEM",
    lat: 41.0606,
    lon: 14.0789,
    elevationM: 10,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirn",
    icao: "LIRN",
    name: "Napoli Capodichino",
    network: "Aeronautica Militare / IEM",
    lat: 40.8848,
    lon: 14.2917,
    elevationM: 72,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirp",
    icao: "LIRP",
    name: "Pisa San Giusto",
    network: "Aeronautica Militare / IEM",
    lat: 43.6825,
    lon: 10.3956,
    elevationM: 2,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirq",
    icao: "LIRQ",
    name: "Firenze Peretola",
    network: "Aeronautica Militare / IEM",
    lat: 43.8086,
    lon: 11.2028,
    elevationM: 38,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirs",
    icao: "LIRS",
    name: "Grosseto",
    network: "Aeronautica Militare / IEM",
    lat: 42.7481,
    lon: 11.0589,
    elevationM: 7,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirt",
    icao: "LIRT",
    name: "Trevico",
    network: "Aeronautica Militare / IEM",
    lat: 41.0467,
    lon: 15.2328,
    elevationM: 1093,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liru",
    icao: "LIRU",
    name: "Roma Urbe",
    network: "Aeronautica Militare / IEM",
    lat: 41.9533,
    lon: 12.4999,
    elevationM: 24,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirv",
    icao: "LIRV",
    name: "Viterbo",
    network: "Aeronautica Militare / IEM",
    lat: 42.4383,
    lon: 12.055,
    elevationM: 300,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirx",
    icao: "LIRX",
    name: "Monte Calamita",
    network: "Aeronautica Militare / IEM",
    lat: 42.73,
    lon: 10.38,
    elevationM: 297,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liry",
    icao: "LIRY",
    name: "Roma (LIRY)",
    network: "Aeronautica Militare / IEM",
    lat: 41.93,
    lon: 12.277,
    elevationM: 31,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "lirz",
    icao: "LIRZ",
    name: "Perugia Sant'Egidio",
    network: "Aeronautica Militare / IEM",
    lat: 43.0972,
    lon: 12.5103,
    elevationM: 205,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "livc",
    icao: "LIVC",
    name: "Monte Cimone",
    network: "Aeronautica Militare / IEM",
    lat: 44.1936,
    lon: 10.7,
    elevationM: 2173,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "livd",
    icao: "LIVD",
    name: "Dobbiaco",
    network: "Aeronautica Militare / IEM",
    lat: 46.73,
    lon: 12.22,
    elevationM: 1226,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "live",
    icao: "LIVE",
    name: "Passo Resia",
    network: "Aeronautica Militare / IEM",
    lat: 46.8333,
    lon: 10.5,
    elevationM: 1800,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "livf",
    icao: "LIVF",
    name: "Frontone",
    network: "Aeronautica Militare / IEM",
    lat: 43.5169,
    lon: 12.7278,
    elevationM: 574,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "livm",
    icao: "LIVM",
    name: "Punta Marina",
    network: "Aeronautica Militare / IEM",
    lat: 44.4414,
    lon: 12.2961,
    elevationM: 6,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "livo",
    icao: "LIVO",
    name: "Tarvisio",
    network: "Aeronautica Militare / IEM",
    lat: 46.5056,
    lon: 13.5861,
    elevationM: 778,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "livp",
    icao: "LIVP",
    name: "Paganella",
    network: "Aeronautica Militare / IEM",
    lat: 46.1434,
    lon: 11.0376,
    elevationM: 2129,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "livr",
    icao: "LIVR",
    name: "Passo Rolle",
    network: "Aeronautica Militare / IEM",
    lat: 46.2978,
    lon: 11.7867,
    elevationM: 2006,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "livt",
    icao: "LIVT",
    name: "Trieste",
    network: "Aeronautica Militare / IEM",
    lat: 45.6767,
    lon: 13.7538,
    elevationM: 20,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
  {
    id: "liyw",
    icao: "LIYW",
    name: "Aviano (USAF)",
    network: "Aeronautica Militare / IEM",
    lat: 46.0303,
    lon: 12.5992,
    elevationM: 126,
    size: "grande",
    measures: ["vento", "pioggia", "temperatura", "umidità"],
  },
];
